feat(editor-client): search collection items
ThemeFuse/Brizy pull request #1889
Opened 2023-06-02 13:30 UTC by nicolaisirghi

2023-06-05 11:10 UTC, victor-pg requested changes

2023-06-05 11:10 UTC, victor-pg commented on public/editor-client/src/types/global.d.ts
need to add also types for `collectionItems`

2023-06-15 11:34 UTC, maxval1 requested changes

2023-06-15 11:34 UTC, maxval1 commented on public/editor-client/src/collectionItems/searchCollectionItems.ts
> +import { getConfig } from "src/config";
use relative import. `./go/to/path`

2023-06-20 10:54 UTC, maxval1 requested changes

2023-06-20 10:54 UTC, maxval1 commented on public/editor-client/src/collectionItems/searchCollectionItems.ts
> +          id: read(ID) ?? ""
Filter all items and exclude items with invalid `ID`

2023-06-20 10:54 UTC, maxval1 commented on public/editor-client/src/collectionItems/utils.ts
> +export const getCollections: GetCollections = async (
move inside `api/index`

2023-06-20 10:54 UTC, maxval1 commented on public/editor-client/src/collectionTypes/loadCollectionTypes.ts
> +        throw new Error(t("Missing postLoopSources in config"));
call `rej()` don't need to create another error here

2023-06-20 10:54 UTC, maxval1 commented on public/editor-client/src/collectionTypes/utils.ts
> +    return (collectionTypes ?? []).map(({ label, name }) => ({
refactor, don't need `collectionTypes ?? [])`

2023-06-20 10:54 UTC, maxval1 commented on public/editor-client/src/config.ts
> +  )
use `mPipe`

2023-06-20 10:54 UTC, maxval1 commented on public/editor-client/src/config.ts
> +
```ts
const collectionTypesReader = (
  arr: Array<Record<string, unknown>>
): Array<CollectionType> => {
  return arr.filter((o): o is CollectionType => !!o.label && !!o.name);
};
```

2023-06-22 06:33 UTC, maxval1 requested changes

2023-06-22 06:33 UTC, maxval1 commented on public/editor-client/src/collectionItems/searchCollectionItems.ts
> +        .filter((item) => item.id);
```ts
const _items = items
        .filter((item) => read(item.ID) );
        .map(({ title, permalink, ID }) => {
          return {
            title,
            permalink,
            id: ID
          };
        })
```

2023-06-22 06:33 UTC, maxval1 commented on public/editor-client/src/config.ts
> +      Arr.readUnknowToRecordReader,
refactror

2023-06-22 06:33 UTC, maxval1 commented on public/editor-client/src/utils/reader/array.ts
> +  );
???

2023-06-22 07:52 UTC, merged