Added elements to editor-client
ThemeFuse/Brizy pull request #1906
Opened 2023-06-28 14:01 UTC by GunkaArtur

Related ticket https://github.com/bagrinsergiu/blox-editor/issues/23303

2023-07-07 10:45 UTC, lift46252 requested changes

2023-07-07 10:45 UTC, lift46252 commented on public/editor-client/src/types/Collections.ts
> +  orderBy: {field: string, label: string}[]
pretify this file

2023-08-01 08:02 UTC, lift46252 commented on public/editor-client/src/types/Collections.ts
> +  orderBy: {field: string, label: string}[]
not fixed

2023-08-02 05:39 UTC, lift46252 approved these changes

2023-08-11 08:12 UTC, lift46252 approved these changes

2023-09-06 08:50 UTC, alecszaharia approved these changes

2023-09-06 08:50 UTC, merged