23851 adobe fonts
ThemeFuse/Brizy pull request #1936
Opened 2023-10-02 11:57 UTC by CristianSpatari

2023-11-09 06:42 UTC, victor-pg requested changes

2023-11-09 06:42 UTC, victor-pg commented on public/editor-client/src/fonts/index.ts
> +  });
use `array.map` for this
```ts
const families = mockTypeKitData.kit.families.map(()=>(
    {
      id: family.id,
      family: family.name,
      category: family.slug,
      kind: "webfonts#webfont",
      subsets: [family.css_names[0]],
      variants: family.variations
    }
  )
)

return {
    kit: {
      id: mockTypeKitData.kit.id,
      families
    }
  }
```

2023-11-09 06:42 UTC, victor-pg commented on brizy.php
rollback

2023-11-09 06:42 UTC, victor-pg commented on public/editor-client/src/fonts/index.ts
> +}
make `types.ts` file and move there

2023-11-09 06:42 UTC, victor-pg commented on public/editor-client/src/fonts/index.ts
> +function convertDataToLocal(mockTypeKitData: KitData): Fonts {
make arrow function

2023-11-09 06:42 UTC, victor-pg commented on public/editor-src/editor/js/redux/actions2.ts
> +  id?: string
review `id`

2023-11-13 07:06 UTC, victor-pg requested changes

2023-11-13 07:06 UTC, victor-pg commented on brizy.php
rollback

2023-11-13 07:06 UTC, victor-pg commented on public/editor-client/src/fonts/index.ts
> +//       hash,
why is commented ?

2024-05-21 06:38 UTC, maxval1 requested changes

2024-05-21 06:38 UTC, maxval1 commented on public/editor-client/src/api/index.ts
> +//#region Screenshots
rename region to AdobeFonts

2024-05-21 06:38 UTC, maxval1 commented on public/editor-client/src/api/index.ts
> +  return request(url, {
transform to `async/await`

2024-05-21 06:38 UTC, maxval1 commented on public/editor-client/src/config.ts
> +        full: optional(
optional?

2024-05-28 11:08 UTC, merged