Added custom icons in editor
ThemeFuse/Brizy pull request #1992
Opened 2024-03-15 09:45 UTC by nicolaisirghi

### Changelog
New: Added custom icons

2024-03-25 07:52 UTC, victor-pg requested changes

2024-03-25 07:52 UTC, victor-pg commented on public/editor-client/src/api/index.ts
> +export const deleteIcon = async (uid: string): Promise<unknown> => {
write concrete type instead of `unknown`

2024-03-25 07:52 UTC, victor-pg commented on public/editor-client/src/config.ts
> +      Str.read
create an fn:
```ts
export const readIconUrl = (url:string)=>pipe(mPipe(Obj.readKey("customIcon", Obj.read, Obj.readKey(url), Str.read)) ,throwOnNullish(`Invalid API: ${url}`))
```
and here use simple:
```ts
deleteIconUrl: readIconUrl("deleteIconUrl")
```

2024-03-28 08:37 UTC, maxval1 requested changes

2024-03-28 08:37 UTC, maxval1 commented on public/editor-client/src/customIcon/index.ts
> +      .catch(() => rej(t("Failed to delete icon")));
1. async/await
2. try/catch

2024-03-28 08:37 UTC, maxval1 commented on public/editor-client/src/api/index.ts
> +    .then((r) => r.data);
1. async/await
2. try/catch

2024-03-28 08:37 UTC, maxval1 commented on public/editor-client/src/index.ts
> +    getIconUrl: config.api.getIconUrl
rename to `iconUrl`

2024-04-25 07:43 UTC, maxval1 requested changes

2024-04-25 07:43 UTC, maxval1 commented on public/editor-client/src/index.ts
> +import { merge } from "lodash";
same as `lodash/set`

2024-05-01 08:45 UTC, merged