WP Ai Global Styles
ThemeFuse/Brizy pull request #1994
Opened 2024-04-04 10:51 UTC by GunkaArtur

Related issue

2024-04-12 12:14 UTC, GunkaArtur commented
URL from config will be added here https://github.com/bagrinsergiu/blox-editor/issues/26071

2024-04-18 06:54 UTC, victor-pg requested changes

2024-04-18 06:54 UTC, victor-pg commented on public/editor-client/src/aiGlobalStyles/index.ts
> +    "https://phplaravel-1109775-4163586.cloudwaysapps.com/api/template";
use url from config

2024-04-18 06:54 UTC, victor-pg commented on public/editor-client/src/aiGlobalStyles/index.ts
> +        const styles = await fetch(`${apiUrl}/style`).then((r) => r.json());
use async/await without `then`:

```ts
const styles = await getStyles(/* ... */)
```

2024-04-18 06:54 UTC, victor-pg commented on public/editor-client/src/aiGlobalStyles/index.ts
> +        const data = await fetch(`${apiUrl}/typography`).then((r) => r.json());
here also use async/await without `then`

2024-04-19 07:58 UTC, GunkaArtur commented on public/editor-client/src/aiGlobalStyles/index.ts
> +    "https://phplaravel-1109775-4163586.cloudwaysapps.com/api/template";
https://github.com/bagrinsergiu/blox-editor/issues/26071

2024-04-26 10:34 UTC, maxval1 requested changes

2024-04-26 10:34 UTC, maxval1 commented on editor/editor/editor.php
> +	        'aiGlobalStyleUrl' => 'https://phplaravel-1109775-4163586.cloudwaysapps.com'
need to be revied

2024-04-26 10:34 UTC, maxval1 commented on public/editor-client/src/aiGlobalStyles/index.ts
> +          `${aiGlobalStyleUrl}/api/template/style`
same as editor api client

2024-05-08 04:50 UTC, victor-pg requested changes

2024-05-08 04:50 UTC, victor-pg commented on public/editor-client/src/aiGlobalStyles/index.ts
> +        rej(t("Failed to load meta.json"));
review reject message

2024-05-08 04:50 UTC, victor-pg commented on public/editor-client/src/aiGlobalStyles/index.ts
> +        rej(t("Failed to load resolves for selected DefaultTemplate"));
review reject message

shouldn't be something like: "failed to load typography..." ?

2024-05-08 04:50 UTC, victor-pg commented on public/editor-client/src/types/DefaultTemplate.ts
> +export interface AiGlobalStyles<T1, T2> {
rename `AiGlobalStyles`

as i see in previous @maxval1 review there is nothing with AI

2024-05-08 04:50 UTC, victor-pg commented on public/editor-client/src/index.ts
> +      getAIGlobalStyles(config)
rename also this function

2024-05-14 11:06 UTC, lift46252 approved these changes

2024-05-17 06:50 UTC, merged