WP beta Stories
ThemeFuse/Brizy pull request #2004
Opened 2024-07-08 07:54 UTC by GunkaArtur

Related issue: https://github.com/bagrinsergiu/blox-editor/issues/25400

2024-07-09 07:28 UTC, victor-pg requested changes

2024-07-09 07:28 UTC, victor-pg commented on public/editor-client/src/api/index.ts
> +    )(res);
apply the same change as in review for cloud api-client

2024-07-09 07:28 UTC, victor-pg commented on public/editor-client/src/defaultTemplates/index.ts
> +          stories: convertStories(templates, `${templatesImageUrl}`),
here is the same story with `${templatesImageUrl}`

should be used simple: stories: `convertStories(templates, templatesImageUrl)`

2024-07-09 07:28 UTC, victor-pg commented on public/editor-client/src/defaultTemplates/utils.ts
> +  return Array.isArray(obj) && obj.every((item) => isDefaultBlock(item));
```ts
return Array.isArray(obj) && obj.every(isDefaultBlock);
```

2024-07-09 07:28 UTC, victor-pg commented on public/editor-client/src/types/DefaultTemplate.ts
> +}
create common type with repated keys and use it as extend for `StoriesAPI` and `StoryPages`

2024-07-10 08:06 UTC, maxval1 requested changes

2024-07-11 12:39 UTC, merged